/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-03-10 21:48:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.transport;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.academictrip.dao.*;
import com.academictrip.model.*;
import java.util.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import com.academictrip.model.User;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1741635984030L));
    _jspx_dependants.put("/includes/transportHeader.jsp", Long.valueOf(1741638226626L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.academictrip.dao");
    _jspx_imports_packages.add("com.academictrip.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("com.academictrip.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Transport Dashboard | Academic Trip System</title>\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/styles.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      out.write('\n');
      out.write('\n');

    // Define these variables here so they're available to all pages that include this header
    String pageName = request.getRequestURI().substring(request.getRequestURI().lastIndexOf("/") + 1);
    User currentUser = (User) session.getAttribute("user");
    
    if (currentUser == null) {
        response.sendRedirect(request.getContextPath() + "/login.jsp");
        return;
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<div class=\"bg-indigo-800 shadow-md\">\n");
      out.write("    <div class=\"max-w-7xl mx-auto px-2 sm:px-4 lg:px-8\">\n");
      out.write("        <div class=\"relative flex items-center justify-between h-16\">\n");
      out.write("            <!-- Mobile menu button -->\n");
      out.write("            <div class=\"absolute inset-y-0 left-0 flex items-center sm:hidden\">\n");
      out.write("                <button type=\"button\" id=\"mobile-menu-button\"\n");
      out.write("                        class=\"inline-flex items-center justify-center p-2 rounded-md text-indigo-200 hover:text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white\">\n");
      out.write("                    <span class=\"sr-only\">Open main menu</span>\n");
      out.write("                    <i class=\"fas fa-bars text-xl\"></i>\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Logo and site name -->\n");
      out.write("            <div class=\"flex-1 flex items-center justify-center sm:items-stretch sm:justify-start\">\n");
      out.write("                <div class=\"flex-shrink-0 flex items-center\">\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard.jsp\" class=\"flex items-center\">\n");
      out.write("                        <i class=\"fas fa-bus-alt text-white text-2xl\"></i>\n");
      out.write("                        <span class=\"ml-2 text-white font-bold text-lg hidden md:block\">ATS Transport</span>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Desktop Navigation -->\n");
      out.write("                <div class=\"hidden sm:block sm:ml-6\">\n");
      out.write("                    <nav class=\"flex space-x-1\">\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/dashboard.jsp\" \n");
      out.write("                           class=\"px-3 py-2 rounded-md text-sm font-medium text-white hover:bg-indigo-600 flex items-center transition-colors ");
      out.print( pageName.equals("dashboard.jsp") ? "bg-indigo-700" : "" );
      out.write("\">\n");
      out.write("                            <i class=\"fas fa-tachometer-alt mr-1\"></i> Dashboard\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/manageDrivers.jsp\" \n");
      out.write("                           class=\"px-3 py-2 rounded-md text-sm font-medium text-white hover:bg-indigo-600 flex items-center transition-colors ");
      out.print( pageName.equals("manageDrivers.jsp") ? "bg-indigo-700" : "" );
      out.write("\">\n");
      out.write("                            <i class=\"fas fa-user-tie mr-1\"></i> Drivers\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/manageVehicles.jsp\" \n");
      out.write("                           class=\"px-3 py-2 rounded-md text-sm font-medium text-white hover:bg-indigo-600 flex items-center transition-colors ");
      out.print( pageName.equals("manageVehicles.jsp") ? "bg-indigo-700" : "" );
      out.write("\">\n");
      out.write("                            <i class=\"fas fa-car mr-1\"></i> Vehicles\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/assignResources.jsp\" \n");
      out.write("                           class=\"px-3 py-2 rounded-md text-sm font-medium text-white hover:bg-indigo-600 flex items-center transition-colors ");
      out.print( pageName.equals("assignResources.jsp") ? "bg-indigo-700" : "" );
      out.write("\">\n");
      out.write("                            <i class=\"fas fa-clipboard-list mr-1\"></i> Assign\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/viewAssignments.jsp\" \n");
      out.write("                           class=\"px-3 py-2 rounded-md text-sm font-medium text-white hover:bg-indigo-600 flex items-center transition-colors ");
      out.print( pageName.equals("viewAssignments.jsp") ? "bg-indigo-700" : "" );
      out.write("\">\n");
      out.write("                            <i class=\"fas fa-list-alt mr-1\"></i> Assignments\n");
      out.write("                        </a>\n");
      out.write("                    </nav>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- User Menu -->\n");
      out.write("            <div class=\"hidden md:block\">\n");
      out.write("                <div class=\"flex items-center\">\n");
      out.write("                    <div class=\"relative ml-3\">\n");
      out.write("                        <button type=\"button\" \n");
      out.write("                                class=\"max-w-xs flex items-center text-sm rounded-full text-white focus:outline-none transition-colors group\"\n");
      out.write("                                id=\"userMenuButton\" \n");
      out.write("                                onclick=\"document.getElementById('userDropdown').classList.toggle('hidden')\">\n");
      out.write("                            <span class=\"bg-indigo-600 p-2 rounded-lg group-hover:bg-indigo-700\">\n");
      out.write("                                <i class=\"fas fa-user-circle text-xl mr-2\"></i>\n");
      out.write("                                ");
 if(currentUser != null) { 
      out.write("\n");
      out.write("                                ");
      out.print( currentUser.getUsername() );
      out.write("\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                                <i class=\"fas fa-chevron-down ml-1 text-xs\"></i>\n");
      out.write("                            </span>\n");
      out.write("                        </button>\n");
      out.write("                        \n");
      out.write("                        <!-- Profile dropdown panel -->\n");
      out.write("                        <div id=\"userDropdown\" class=\"hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none z-10\" role=\"menu\" aria-orientation=\"vertical\" aria-labelledby=\"user-menu-button\">\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/profile.jsp\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\" role=\"menuitem\">\n");
      out.write("                                <i class=\"fas fa-user mr-2\"></i> Your Profile\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/settings.jsp\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\" role=\"menuitem\">\n");
      out.write("                                <i class=\"fas fa-cog mr-2\"></i> Settings\n");
      out.write("                            </a>\n");
      out.write("                            <hr class=\"my-1\">\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\" role=\"menuitem\">\n");
      out.write("                                <i class=\"fas fa-sign-out-alt mr-2\"></i> Sign out\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Mobile menu, show/hide based on menu state -->\n");
      out.write("    <div class=\"sm:hidden hidden\" id=\"mobile-menu\">\n");
      out.write("        <div class=\"px-2 pt-2 pb-3 space-y-1 bg-indigo-800 border-t border-indigo-700\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/dashboard.jsp\" \n");
      out.write("               class=\"block px-3 py-2 rounded-md text-base font-medium text-white hover:bg-indigo-600 transition-colors ");
      out.print( pageName.equals("dashboard.jsp") ? "bg-indigo-700" : "" );
      out.write("\">\n");
      out.write("                <i class=\"fas fa-tachometer-alt mr-2\"></i> Dashboard\n");
      out.write("            </a>\n");
      out.write("            \n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/manageDrivers.jsp\" \n");
      out.write("               class=\"block px-3 py-2 rounded-md text-base font-medium text-white hover:bg-indigo-600 transition-colors ");
      out.print( pageName.equals("manageDrivers.jsp") ? "bg-indigo-700" : "" );
      out.write("\">\n");
      out.write("                <i class=\"fas fa-user-tie mr-2\"></i> Manage Drivers\n");
      out.write("            </a>\n");
      out.write("            \n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/manageVehicles.jsp\" \n");
      out.write("               class=\"block px-3 py-2 rounded-md text-base font-medium text-white hover:bg-indigo-600 transition-colors ");
      out.print( pageName.equals("manageVehicles.jsp") ? "bg-indigo-700" : "" );
      out.write("\">\n");
      out.write("                <i class=\"fas fa-car mr-2\"></i> Manage Vehicles\n");
      out.write("            </a>\n");
      out.write("            \n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/assignResources.jsp\" \n");
      out.write("               class=\"block px-3 py-2 rounded-md text-base font-medium text-white hover:bg-indigo-600 transition-colors ");
      out.print( pageName.equals("assignResources.jsp") ? "bg-indigo-700" : "" );
      out.write("\">\n");
      out.write("                <i class=\"fas fa-clipboard-list mr-2\"></i> Assign Resources\n");
      out.write("            </a>\n");
      out.write("            \n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/viewAssignments.jsp\" \n");
      out.write("               class=\"block px-3 py-2 rounded-md text-base font-medium text-white hover:bg-indigo-600 transition-colors ");
      out.print( pageName.equals("viewAssignments.jsp") ? "bg-indigo-700" : "" );
      out.write("\">\n");
      out.write("                <i class=\"fas fa-list-alt mr-2\"></i> View Assignments\n");
      out.write("            </a>\n");
      out.write("            \n");
      out.write("            <hr class=\"border-indigo-600 my-2\">\n");
      out.write("            \n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/profile.jsp\" \n");
      out.write("               class=\"block px-3 py-2 rounded-md text-base font-medium text-white hover:bg-indigo-600 transition-colors\">\n");
      out.write("                <i class=\"fas fa-user mr-2\"></i> Your Profile\n");
      out.write("            </a>\n");
      out.write("            \n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/settings.jsp\" \n");
      out.write("               class=\"block px-3 py-2 rounded-md text-base font-medium text-white hover:bg-indigo-600 transition-colors\">\n");
      out.write("                <i class=\"fas fa-cog mr-2\"></i> Settings\n");
      out.write("            </a>\n");
      out.write("            \n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" \n");
      out.write("               class=\"block px-3 py-2 rounded-md text-base font-medium text-white hover:bg-indigo-600 transition-colors\">\n");
      out.write("                <i class=\"fas fa-sign-out-alt mr-2\"></i> Sign out\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    // Toggle mobile menu\n");
      out.write("    document.getElementById('mobile-menu-button').addEventListener('click', function() {\n");
      out.write("        document.getElementById('mobile-menu').classList.toggle('hidden');\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    // Close dropdown when clicking outside\n");
      out.write("    document.addEventListener('click', function(event) {\n");
      out.write("        const userMenuButton = document.getElementById('userMenuButton');\n");
      out.write("        const userDropdown = document.getElementById('userDropdown');\n");
      out.write("        \n");
      out.write("        if (userMenuButton && userDropdown && !userMenuButton.contains(event.target) && !userDropdown.contains(event.target)) {\n");
      out.write("            userDropdown.classList.add('hidden');\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"page-title\">\n");
      out.write("            <h1 class=\"text-2xl font-bold text-gray-800\"><i class=\"fas fa-tachometer-alt mr-2\"></i>Transport Dashboard</h1>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        ");

            // Get counts for dashboard
            TripDAO tripDAO = new TripDAO();
            DriverDAO driverDAO = new DriverDAO();
            VehicleDAO vehicleDAO = new VehicleDAO();
            
            // Get available trips
            List<Trip> allTrips = tripDAO.getAllTrips();
            int pendingTrips = 0;
            int assignedTrips = 0;
            
            // Count pending vs assigned trips - use driverVehicleId to check assignment
            for (Trip trip : allTrips) {
                if (trip.getDriverVehicleId() != null && !trip.getDriverVehicleId().isEmpty()) {
                    assignedTrips++;
                } else {
                    pendingTrips++;
                }
            }
            
            int totalDrivers = driverDAO.getAllDrivers().size();
            int totalVehicles = vehicleDAO.getAllVehicles().size();
            
            // Get most recent trips - using limited number from all trips
            List<Trip> recentTrips = allTrips.size() > 5 ? allTrips.subList(0, 5) : allTrips;
        
      out.write("\n");
      out.write("        \n");
      out.write("        <!-- Dashboard Cards -->\n");
      out.write("        <div class=\"transport-dashboard animate-fade\">\n");
      out.write("            <div class=\"dashboard-card\">\n");
      out.write("                <i class=\"fas fa-route\"></i>\n");
      out.write("                <h3>");
      out.print( pendingTrips );
      out.write("</h3>\n");
      out.write("                <p>Pending Trip Assignments</p>\n");
      out.write("                <a href=\"assignResources.jsp\" class=\"btn btn-sm\">Assign Resources</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"dashboard-card\">\n");
      out.write("                <i class=\"fas fa-bus\"></i>\n");
      out.write("                <h3>");
      out.print( totalVehicles );
      out.write("</h3>\n");
      out.write("                <p>Available Vehicles</p>\n");
      out.write("                <a href=\"manageVehicles.jsp\" class=\"btn btn-sm\">Manage Vehicles</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"dashboard-card\">\n");
      out.write("                <i class=\"fas fa-id-card\"></i>\n");
      out.write("                <h3>");
      out.print( totalDrivers );
      out.write("</h3>\n");
      out.write("                <p>Registered Drivers</p>\n");
      out.write("                <a href=\"manageDrivers.jsp\" class=\"btn btn-sm\">Manage Drivers</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"dashboard-card\">\n");
      out.write("                <i class=\"fas fa-check-circle\"></i>\n");
      out.write("                <h3>");
      out.print( assignedTrips );
      out.write("</h3>\n");
      out.write("                <p>Assigned Trips</p>\n");
      out.write("                <a href=\"viewAssignments.jsp\" class=\"btn btn-sm\">View Assignments</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Quick Actions Card -->\n");
      out.write("        <div class=\"card mb-5\">\n");
      out.write("            <div class=\"card-header\">\n");
      out.write("                <h2 class=\"card-title\"><i class=\"fas fa-bolt mr-2\"></i>Quick Actions</h2>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("                <div class=\"grid grid-cols-1 md:grid-cols-3 gap-3\">\n");
      out.write("                    <a href=\"manageDrivers.jsp\" class=\"quick-action-card bg-blue-500\">\n");
      out.write("                        <i class=\"fas fa-users\"></i>\n");
      out.write("                        <span>Manage Drivers</span>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"manageVehicles.jsp\" class=\"quick-action-card bg-green-500\">\n");
      out.write("                        <i class=\"fas fa-car\"></i>\n");
      out.write("                        <span>Manage Vehicles</span>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"assignResources.jsp\" class=\"quick-action-card bg-purple-500\">\n");
      out.write("                        <i class=\"fas fa-clipboard-list\"></i>\n");
      out.write("                        <span>Assign Resources</span>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Recent Trips Section -->\n");
      out.write("        <div class=\"card mt-5\">\n");
      out.write("            <div class=\"card-header\">\n");
      out.write("                <h2 class=\"card-title\"><i class=\"fas fa-history mr-2\"></i>Recent Trip Assignments</h2>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"card-body p-0\">\n");
      out.write("                <div class=\"table-container\">\n");
      out.write("                    <table>\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                                <th>Trip ID</th>\n");
      out.write("                                <th>Destination</th>\n");
      out.write("                                <th>Start Date</th>\n");
      out.write("                                <th>End Date</th>\n");
      out.write("                                <th>Status</th>\n");
      out.write("                                <th>Actions</th>\n");
      out.write("                            </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                            ");
 if(recentTrips != null && !recentTrips.isEmpty()) { 
                                for(Trip trip : recentTrips) {
                                    String statusClass = "pending";
                                    String statusText = "Pending";
                                    
                                    if (trip.getDriverVehicleId() != null && !trip.getDriverVehicleId().isEmpty()) {
                                        statusClass = "assigned";
                                        statusText = "Assigned";
                                    }
                            
      out.write("\n");
      out.write("                            <tr>\n");
      out.write("                                <td>");
      out.print( trip.getTripId() );
      out.write("</td>\n");
      out.write("                                <td>");
      out.print( trip.getDestinationId() != null ? trip.getDestinationId() : "Not specified" );
      out.write("</td>\n");
      out.write("                                <td>");
      out.print( trip.getStartDateFormatted() != null ? trip.getStartDateFormatted() : "Not set" );
      out.write("</td>\n");
      out.write("                                <td>");
      out.print( trip.getEndDateFormatted() != null ? trip.getEndDateFormatted() : "Not set" );
      out.write("</td>\n");
      out.write("                                <td><span class=\"trip-status ");
      out.print( statusClass );
      out.write('"');
      out.write('>');
      out.print( statusText );
      out.write("</span></td>\n");
      out.write("                                <td>\n");
      out.write("                                    <a href=\"tripDetails.jsp?id=");
      out.print( trip.getTripId() );
      out.write("\" class=\"btn btn-sm btn-primary\">View</a>\n");
      out.write("                                </td>\n");
      out.write("                            </tr>\n");
      out.write("                            ");
 } } else { 
      out.write("\n");
      out.write("                            <tr>\n");
      out.write("                                <td colspan=\"6\" class=\"text-center py-4\">No recent trips found</td>\n");
      out.write("                            </tr>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Quick Links -->\n");
      out.write("        <div class=\"card mt-4\">\n");
      out.write("            <div class=\"card-header\">\n");
      out.write("                <h2 class=\"card-title\"><i class=\"fas fa-link mr-2\"></i>Quick Links</h2>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("                <div class=\"grid grid-cols-1 md:grid-cols-3 gap-4\">\n");
      out.write("                    <a href=\"assignResources.jsp\" class=\"btn btn-primary w-full\">\n");
      out.write("                        <i class=\"fas fa-tasks mr-2\"></i>Assign Trip Resources\n");
      out.write("                    </a>\n");
      out.write("                    \n");
      out.write("                    <a href=\"viewAssignments.jsp\" class=\"btn btn-info w-full\">\n");
      out.write("                        <i class=\"fas fa-clipboard-list mr-2\"></i>View All Assignments\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    ");
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"bg-indigo-900 text-white mt-auto py-6\">\n");
      out.write("    <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\n");
      out.write("        <div class=\"md:flex md:items-center md:justify-between\">\n");
      out.write("            <div class=\"flex justify-center md:order-2 space-x-6\">\n");
      out.write("                <a href=\"#\" class=\"text-gray-300 hover:text-white\">\n");
      out.write("                    <span class=\"sr-only\">Help Center</span>\n");
      out.write("                    <i class=\"fas fa-question-circle text-xl\"></i>\n");
      out.write("                </a>\n");
      out.write("                <a href=\"#\" class=\"text-gray-300 hover:text-white\">\n");
      out.write("                    <span class=\"sr-only\">Contact Support</span>\n");
      out.write("                    <i class=\"fas fa-headset text-xl\"></i>\n");
      out.write("                </a>\n");
      out.write("                <a href=\"#\" class=\"text-gray-300 hover:text-white\">\n");
      out.write("                    <span class=\"sr-only\">Privacy Policy</span>\n");
      out.write("                    <i class=\"fas fa-shield-alt text-xl\"></i>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"mt-8 md:mt-0 md:order-1 text-center md:text-left\">\n");
      out.write("                <p class=\"text-base text-gray-300\">&copy; ");
      out.print( java.time.Year.now().getValue() );
      out.write(" Academic Trip System. All rights reserved.</p>\n");
      out.write("                <p class=\"text-sm text-gray-400 mt-1\">Version 1.0.0</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- Add to bottom of page to prevent FOUC (Flash of Unstyled Content) -->\n");
      out.write("<script>\n");
      out.write("    // Apply any custom theme preferences if stored\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("        // Check for any stored theme preferences and apply them\n");
      out.write("        const theme = localStorage.getItem('ats-theme');\n");
      out.write("        if (theme === 'dark') {\n");
      out.write("            // Add dark mode classes if we implement dark mode in the future\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
