/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-03-10 23:12:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.transport;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.academictrip.dao.*;
import com.academictrip.model.*;
import java.util.*;
import java.time.format.*;
import java.time.LocalDate;

public final class tripDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.time.format");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.academictrip.dao");
    _jspx_imports_packages.add("com.academictrip.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.time.LocalDate");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    // Get trip ID from request parameter
    String tripIdParam = request.getParameter("id");
    
    // Initialize objects
    Trip trip = null;
    DriverVehicle assignment = null;
    Driver driver = null;
    Vehicle vehicle = null;
    Destination destination = null;
    InchargeGroup inchargeGroup = null;
    Incharge incharge = null;
    TripGroup tripGroup = null;
    Course course = null;
    
    // Format dates nicely
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MMM d, yyyy");
    
    if(tripIdParam != null && !tripIdParam.trim().isEmpty()) {
        try {
            TripDAO tripDAO = new TripDAO();
            trip = tripDAO.getTripById(tripIdParam);
            
            if(trip != null) {
                // Get driver-vehicle assignment
                DriverVehicleDAO driverVehicleDAO = new DriverVehicleDAO();
                assignment = driverVehicleDAO.getAssignmentById(trip.getDriverVehicleId());
                
                // Get destination details
                DestinationDAO destinationDAO = new DestinationDAO();
                if(trip.getDestinationId() != null) {
                    destination = destinationDAO.getDestinationById(trip.getDestinationId());
                }
                
                // Get incharge group information
                InchargeGroupDAO inchargeGroupDAO = new InchargeGroupDAO();
                if(trip.getInchargeGroupId() != null) {
                    inchargeGroup = inchargeGroupDAO.getInchargeGroupById(trip.getInchargeGroupId());
                    if(inchargeGroup != null) {
                        InchargeDAO inchargeDAO = new InchargeDAO();
                        incharge = inchargeDAO.getInchargeById(inchargeGroup.getInchargeId());
                    }
                }
                
                // Get trip group and course information
                if(inchargeGroup != null) {
                    TripGroupDAO tripGroupDAO = new TripGroupDAO();
                    tripGroup = tripGroupDAO.getGroupById(inchargeGroup.getGroupId());
                    if(tripGroup != null) {
                        CourseDAO courseDAO = new CourseDAO();
                        course = courseDAO.getCourseById(tripGroup.getCourseId());
                    }
                }
                
                // Get driver and vehicle details if assigned
                if(assignment != null) {
                    DriverDAO driverDAO = new DriverDAO();
                    VehicleDAO vehicleDAO = new VehicleDAO();
                    
                    if(assignment.getDriverId() != null) {
                        driver = driverDAO.getDriverById(assignment.getDriverId());
                    }
                    
                    if(assignment.getVehicleId() != null) {
                        vehicle = vehicleDAO.getVehicleById(assignment.getVehicleId());
                    }
                }
            }
        } catch(Exception e) {
            e.printStackTrace();
            request.setAttribute("errorMessage", "Error retrieving trip details: " + e.getMessage());
        }
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Trip Details | Academic Trip System</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/styles.css\">\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-gray-50\">\n");
      out.write("    <div class=\"page-wrapper\">\n");
      out.write("        <!-- Include standardized header -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../includes/transportHeader.jsp", out, false);
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"container mx-auto px-4 py-8\">\n");
      out.write("                <!-- Page header with navigation -->\n");
      out.write("                <div class=\"flex items-center space-x-4 mb-8\">\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/viewAssignments.jsp\" class=\"text-gray-500 hover:text-indigo-600\">\n");
      out.write("                        <i class=\"fas fa-arrow-left\"></i> Back to Assignments\n");
      out.write("                    </a>\n");
      out.write("                    <h1 class=\"text-3xl font-bold text-gray-900\">\n");
      out.write("                        Trip Details\n");
      out.write("                    </h1>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                ");
 if(trip == null) { 
      out.write("\n");
      out.write("                    <div class=\"bg-red-50 border-l-4 border-red-500 p-4 mb-6\">\n");
      out.write("                        <div class=\"flex\">\n");
      out.write("                            <div class=\"flex-shrink-0\">\n");
      out.write("                                <i class=\"fas fa-exclamation-circle text-red-500\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"ml-3\">\n");
      out.write("                                <p class=\"text-red-700\">\n");
      out.write("                                    Trip not found. Please check the ID and try again.\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"text-center py-8\">\n");
      out.write("                        <i class=\"fas fa-search text-gray-300 text-4xl mb-4\"></i>\n");
      out.write("                        <p class=\"text-xl text-gray-400\">Trip details could not be found</p>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/viewAssignments.jsp\" class=\"inline-block mt-4 bg-indigo-600 hover:bg-indigo-700 text-white py-2 px-4 rounded-md\">\n");
      out.write("                            View All Assignments\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    <!-- Trip Status Banner -->\n");
      out.write("                    ");

                        String statusClass, statusText, statusIcon;
                        LocalDate today = LocalDate.now();
                        if(today.isBefore(trip.getDepartureDate())) {
                            statusClass = "bg-blue-50 border-blue-500 text-blue-800";
                            statusText = "Upcoming Trip";
                            statusIcon = "calendar-alt";
                        } else if(today.isAfter(trip.getReturnDate())) {
                            statusClass = "bg-gray-50 border-gray-500 text-gray-800";
                            statusText = "Completed Trip";
                            statusIcon = "check-circle";
                        } else {
                            statusClass = "bg-green-50 border-green-500 text-green-800";
                            statusText = "Ongoing Trip";
                            statusIcon = "route";
                        }
                    
      out.write("\n");
      out.write("                    <div class=\"");
      out.print( statusClass );
      out.write(" border-l-4 p-4 mb-6 rounded-r-md\">\n");
      out.write("                        <div class=\"flex\">\n");
      out.write("                            <div class=\"flex-shrink-0\">\n");
      out.write("                                <i class=\"fas fa-");
      out.print( statusIcon );
      out.write("\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"ml-3\">\n");
      out.write("                                <p class=\"font-medium\">");
      out.print( statusText );
      out.write("</p>\n");
      out.write("                                <p class=\"text-sm\">ID: ");
      out.print( trip.getTripId() );
      out.write("</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"grid grid-cols-1 md:grid-cols-3 gap-6\">\n");
      out.write("                        <!-- Main Trip Information -->\n");
      out.write("                        <div class=\"md:col-span-2\">\n");
      out.write("                            <div class=\"bg-white rounded-lg shadow-md p-6 mb-6\">\n");
      out.write("                                <h2 class=\"text-xl font-bold mb-4 text-blue-800 border-b pb-2\">\n");
      out.write("                                    <i class=\"fas fa-info-circle mr-2\"></i>Trip Information\n");
      out.write("                                </h2>\n");
      out.write("                                <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\">\n");
      out.write("                                    <div>\n");
      out.write("                                        <p class=\"text-gray-600 font-medium\">Trip ID:</p>\n");
      out.write("                                        <p class=\"font-semibold\">");
      out.print( trip.getTripId() );
      out.write("</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <p class=\"text-gray-600 font-medium\">Trip Status:</p>\n");
      out.write("                                        <p class=\"font-semibold\">");
      out.print( statusText );
      out.write("</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <p class=\"text-gray-600 font-medium\">Destination:</p>\n");
      out.write("                                        <p class=\"font-semibold\">");
      out.print( destination != null ? destination.getName() : "Not specified" );
      out.write("</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <p class=\"text-gray-600 font-medium\">Purpose:</p>\n");
      out.write("                                        <p class=\"font-semibold\">");
      out.print( trip.getPurpose() != null ? trip.getPurpose() : "Academic Trip" );
      out.write("</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <p class=\"text-gray-600 font-medium\">Departure Date:</p>\n");
      out.write("                                        <p class=\"font-semibold\">");
      out.print( formatter.format(trip.getDepartureDate()) );
      out.write("</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <p class=\"text-gray-600 font-medium\">Return Date:</p>\n");
      out.write("                                        <p class=\"font-semibold\">");
      out.print( formatter.format(trip.getReturnDate()) );
      out.write("</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <p class=\"text-gray-600 font-medium\">Duration:</p>\n");
      out.write("                                        <p class=\"font-semibold\">\n");
      out.write("                                            ");
      out.print( java.time.temporal.ChronoUnit.DAYS.between(trip.getDepartureDate(), trip.getReturnDate()) + 1 );
      out.write(" days\n");
      out.write("                                        </p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <p class=\"text-gray-600 font-medium\">Course:</p>\n");
      out.write("                                        <p class=\"font-semibold\">\n");
      out.write("                                            ");
      out.print( course != null ? course.getCourseName() : "Not specified" );
      out.write("\n");
      out.write("                                        </p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            \n");
      out.write("                            <!-- Incharge Information -->\n");
      out.write("                            <div class=\"bg-white rounded-lg shadow-md p-6 mb-6\">\n");
      out.write("                                <h2 class=\"text-xl font-bold mb-4 text-blue-800 border-b pb-2\">\n");
      out.write("                                    <i class=\"fas fa-user-tie mr-2\"></i>Trip Incharge Details\n");
      out.write("                                </h2>\n");
      out.write("                                ");
 if(incharge != null) { 
      out.write("\n");
      out.write("                                    <div class=\"flex items-center mb-4\">\n");
      out.write("                                        <div class=\"h-12 w-12 rounded-full bg-blue-100 flex items-center justify-center\">\n");
      out.write("                                            <i class=\"fas fa-user text-blue-500\"></i>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"ml-4\">\n");
      out.write("                                            <h3 class=\"text-lg font-semibold\">");
      out.print( incharge.getFirstName() );
      out.write(' ');
      out.print( incharge.getLastName() );
      out.write("</h3>\n");
      out.write("                                            <p class=\"text-gray-500\">");
      out.print( incharge.getFacultyId() != null ? "Faculty ID: " + incharge.getFacultyId() : "" );
      out.write("</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4 mt-4\">\n");
      out.write("                                        <div>\n");
      out.write("                                            <p class=\"text-gray-600 font-medium\">Email:</p>\n");
      out.write("                                            <p class=\"font-semibold\">");
      out.print( incharge.getEmail() );
      out.write("</p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div>\n");
      out.write("                                            <p class=\"text-gray-600 font-medium\">Phone:</p>\n");
      out.write("                                            <p class=\"font-semibold\">");
      out.print( incharge.getPhoneNumber() );
      out.write("</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                ");
 } else { 
      out.write("\n");
      out.write("                                    <p class=\"text-gray-500\">No incharge information available for this trip.</p>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                            \n");
      out.write("                            <!-- Student Group Information -->\n");
      out.write("                            <div class=\"bg-white rounded-lg shadow-md p-6\">\n");
      out.write("                                <h2 class=\"text-xl font-bold mb-4 text-blue-800 border-b pb-2\">\n");
      out.write("                                    <i class=\"fas fa-users mr-2\"></i>Student Group Details\n");
      out.write("                                </h2>\n");
      out.write("                                ");
 if(tripGroup != null) { 
      out.write("\n");
      out.write("                                    <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\">\n");
      out.write("                                        <div>\n");
      out.write("                                            <p class=\"text-gray-600 font-medium\">Group Name:</p>\n");
      out.write("                                            <p class=\"font-semibold\">");
      out.print( tripGroup.getGroupName() != null ? tripGroup.getGroupName() : "Group " + tripGroup.getGroupId() );
      out.write("</p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div>\n");
      out.write("                                            <p class=\"text-gray-600 font-medium\">Number of Students:</p>\n");
      out.write("                                            <p class=\"font-semibold\">");
      out.print( tripGroup.getStudentNumber() );
      out.write("</p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div>\n");
      out.write("                                            <p class=\"text-gray-600 font-medium\">Course:</p>\n");
      out.write("                                            <p class=\"font-semibold\">");
      out.print( course != null ? course.getCourseName() : "Not specified" );
      out.write("</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                ");
 } else { 
      out.write("\n");
      out.write("                                    <p class=\"text-gray-500\">No student group information available for this trip.</p>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <!-- Transport Assignment Details -->\n");
      out.write("                        <div class=\"md:col-span-1\">\n");
      out.write("                            <div class=\"bg-white rounded-lg shadow-md p-6 mb-6 border-t-4 border-secondary\">\n");
      out.write("                                <h2 class=\"text-xl font-bold mb-4 text-blue-800 border-b pb-2\">\n");
      out.write("                                    <i class=\"fas fa-shuttle-van mr-2\"></i>Transport Details\n");
      out.write("                                </h2>\n");
      out.write("                                \n");
      out.write("                                ");
 if(assignment != null && driver != null && vehicle != null) { 
      out.write("\n");
      out.write("                                    <!-- Driver Information -->\n");
      out.write("                                    <div class=\"mb-6\">\n");
      out.write("                                        <h3 class=\"text-lg font-semibold text-gray-700 mb-3\">Assigned Driver</h3>\n");
      out.write("                                        <div class=\"flex items-center mb-4\">\n");
      out.write("                                            <div class=\"h-12 w-12 rounded-full bg-blue-100 flex items-center justify-center\">\n");
      out.write("                                                <i class=\"fas fa-user text-blue-500\"></i>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"ml-4\">\n");
      out.write("                                                <h4 class=\"text-md font-semibold\">");
      out.print( driver.getFirstname() );
      out.write(' ');
      out.print( driver.getLastname() );
      out.write("</h4>\n");
      out.write("                                                <p class=\"text-sm text-gray-500\">Driver ID: ");
      out.print( driver.getDriverId() );
      out.write("</p>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"grid grid-cols-1 gap-2\">\n");
      out.write("                                            <div class=\"flex items-center\">\n");
      out.write("                                                <i class=\"fas fa-phone w-5 text-gray-500\"></i>\n");
      out.write("                                                <span class=\"ml-2\">");
      out.print( driver.getPhoneNumber() );
      out.write("</span>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"flex items-center\">\n");
      out.write("                                                <i class=\"fas fa-envelope w-5 text-gray-500\"></i>\n");
      out.write("                                                <span class=\"ml-2\">");
      out.print( driver.getEmail() );
      out.write("</span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    \n");
      out.write("                                    <!-- Vehicle Information -->\n");
      out.write("                                    <div>\n");
      out.write("                                        <h3 class=\"text-lg font-semibold text-gray-700 mb-3\">Assigned Vehicle</h3>\n");
      out.write("                                        <div class=\"flex items-center mb-4\">\n");
      out.write("                                            <div class=\"h-12 w-12 rounded-full bg-indigo-100 flex items-center justify-center\">\n");
      out.write("                                                <i class=\"fas fa-");
      out.print( vehicle.getType().toLowerCase().contains("bus") ? "bus" : "car" );
      out.write(" text-indigo-500\"></i>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"ml-4\">\n");
      out.write("                                                <h4 class=\"text-md font-semibold\">");
      out.print( vehicle.getMake() );
      out.write(' ');
      out.print( vehicle.getModel() );
      out.write("</h4>\n");
      out.write("                                                <p class=\"text-sm text-gray-500\">");
      out.print( vehicle.getRegistration() );
      out.write("</p>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"grid grid-cols-1 gap-2\">\n");
      out.write("                                            <div class=\"flex items-center\">\n");
      out.write("                                                <i class=\"fas fa-tag w-5 text-gray-500\"></i>\n");
      out.write("                                                <span class=\"ml-2\">");
      out.print( vehicle.getType() );
      out.write("</span>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"flex items-center\">\n");
      out.write("                                                <i class=\"fas fa-calendar w-5 text-gray-500\"></i>\n");
      out.write("                                                <span class=\"ml-2\">");
      out.print( vehicle.getYear() );
      out.write("</span>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"flex items-center\">\n");
      out.write("                                                <i class=\"fas fa-users w-5 text-gray-500\"></i>\n");
      out.write("                                                <span class=\"ml-2\">");
      out.print( vehicle.getCapacity() );
      out.write(" passengers</span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                ");
 } else { 
      out.write("\n");
      out.write("                                    <div class=\"bg-yellow-50 p-4 rounded-md\">\n");
      out.write("                                        <p class=\"text-yellow-700 flex items-center\">\n");
      out.write("                                            <i class=\"fas fa-exclamation-triangle mr-2\"></i>\n");
      out.write("                                            No transport assigned yet\n");
      out.write("                                        </p>\n");
      out.write("                                        <p class=\"text-sm text-yellow-600 mt-1\">\n");
      out.write("                                            This trip doesn't have a driver and vehicle assigned.\n");
      out.write("                                        </p>\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/assignResources.jsp?tripId=");
      out.print( trip.getTripId() );
      out.write("\" \n");
      out.write("                                           class=\"mt-3 inline-block bg-secondary hover:bg-orange-700 text-white py-2 px-4 rounded text-sm\">\n");
      out.write("                                            Assign Resources\n");
      out.write("                                        </a>\n");
      out.write("                                    </div>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                            \n");
      out.write("                            <!-- Action Buttons -->\n");
      out.write("                            <div class=\"bg-white rounded-lg shadow-md p-6\">\n");
      out.write("                                <h2 class=\"text-xl font-bold mb-4 text-blue-800 border-b pb-2\">\n");
      out.write("                                    <i class=\"fas fa-cogs mr-2\"></i>Actions\n");
      out.write("                                </h2>\n");
      out.write("                                <div class=\"space-y-3\">\n");
      out.write("                                    ");
 if(assignment == null) { 
      out.write("\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/assignResources.jsp?tripId=");
      out.print( trip.getTripId() );
      out.write("\" \n");
      out.write("                                           class=\"block w-full bg-green-600 hover:bg-green-700 text-white text-center py-2 px-4 rounded\">\n");
      out.write("                                            <i class=\"fas fa-plus-circle mr-2\"></i> Assign Resources\n");
      out.write("                                        </a>\n");
      out.write("                                    ");
 } else if(LocalDate.now().isBefore(trip.getDepartureDate())) { 
      out.write("\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/editAssignment.jsp?id=");
      out.print( trip.getTripId() );
      out.write("\" \n");
      out.write("                                           class=\"block w-full bg-blue-600 hover:bg-blue-700 text-white text-center py-2 px-4 rounded\">\n");
      out.write("                                            <i class=\"fas fa-edit mr-2\"></i> Edit Assignment\n");
      out.write("                                        </a>\n");
      out.write("                                        <button onclick=\"confirmUnassign('");
      out.print( trip.getTripId() );
      out.write("', '");
      out.print( destination != null ? destination.getName() : "this trip" );
      out.write("')\" \n");
      out.write("                                                class=\"block w-full bg-red-600 hover:bg-red-700 text-white text-center py-2 px-4 rounded\">\n");
      out.write("                                            <i class=\"fas fa-unlink mr-2\"></i> Remove Assignment\n");
      out.write("                                        </button>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/viewAssignments.jsp\" \n");
      out.write("                                       class=\"block w-full bg-gray-500 hover:bg-gray-600 text-white text-center py-2 px-4 rounded\">\n");
      out.write("                                        <i class=\"fas fa-arrow-left mr-2\"></i> Back to Assignments\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <footer>\n");
      out.write("            <div class=\"footer-content\">\n");
      out.write("                <p>&copy; 2023 Academic Trip System. All rights reserved.</p>\n");
      out.write("                <p class=\"mt-2 text-sm text-gray-300\">Transport Management Module</p>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Unassign Confirmation Modal -->\n");
      out.write("    <div id=\"unassignModal\" class=\"fixed z-10 inset-0 overflow-y-auto hidden\">\n");
      out.write("        <div class=\"flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center\">\n");
      out.write("            <div class=\"fixed inset-0 transition-opacity\" aria-hidden=\"true\">\n");
      out.write("                <div class=\"absolute inset-0 bg-gray-500 opacity-75\" onclick=\"closeModal('unassignModal')\"></div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full\">\n");
      out.write("                <div class=\"bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4\">\n");
      out.write("                    <div class=\"sm:flex sm:items-start\">\n");
      out.write("                        <div class=\"mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10\">\n");
      out.write("                            <i class=\"fas fa-exclamation-triangle text-red-600\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left\">\n");
      out.write("                            <h3 class=\"text-lg leading-6 font-medium text-gray-900\" id=\"modal-title\">\n");
      out.write("                                Remove Assignment\n");
      out.write("                            </h3>\n");
      out.write("                            <div class=\"mt-2\">\n");
      out.write("                                <p class=\"text-sm text-gray-500\" id=\"unassignConfirmationText\">\n");
      out.write("                                    Are you sure you want to remove this assignment? This will free up the driver and vehicle for other trips.\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <form id=\"unassignForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/unassignResources\" method=\"post\">\n");
      out.write("                    <input type=\"hidden\" id=\"unassignTripId\" name=\"tripId\">\n");
      out.write("                    <div class=\"bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse\">\n");
      out.write("                        <button type=\"submit\" class=\"w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-red-600 text-base font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:ml-3 sm:w-auto sm:text-sm\">\n");
      out.write("                            Remove Assignment\n");
      out.write("                        </button>\n");
      out.write("                        <button type=\"button\" onclick=\"closeModal('unassignModal')\" class=\"mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm\">\n");
      out.write("                            Cancel\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        function confirmUnassign(tripId, destination) {\n");
      out.write("            document.getElementById('unassignTripId').value = tripId;\n");
      out.write("            document.getElementById('unassignConfirmationText').textContent = \n");
      out.write("                `Are you sure you want to remove the assignment for the trip to ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${destination}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("? This will free up the driver and vehicle for other trips.`;\n");
      out.write("            document.getElementById('unassignModal').classList.remove('hidden');\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function closeModal(modalId) {\n");
      out.write("            document.getElementById(modalId).classList.add('hidden');\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        document.addEventListener('keydown', function(e) {\n");
      out.write("            if (e.key === 'Escape') {\n");
      out.write("                closeModal('unassignModal');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
