/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-03-11 09:36:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.lecturer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.academictrip.dao.TripDAO;
import com.academictrip.model.Trip;
import com.academictrip.model.User;
import java.util.List;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import com.academictrip.model.User;

public final class viewTimetable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1741685744110L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("com.academictrip.dao.TripDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.academictrip.model.Trip");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("com.academictrip.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    User tripTableUser = (User) session.getAttribute("user");
    if (tripTableUser == null || !tripTableUser.getRole().equalsIgnoreCase("lecturer")) {
        response.sendRedirect(request.getContextPath() + "/login.jsp");
        return;
    }
    
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMM yyyy");

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Trip Timetable | Academic Trip System</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/styles.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-gray-50\">\n");
      out.write("    <div class=\"page-wrapper\">\n");
      out.write("        ");
      out.write('\n');
      out.write('\n');

    User headerUser = (User) session.getAttribute("user");
    String userRole = headerUser != null ? headerUser.getRole() : "";
    boolean isLecturerRole = "lecturer".equalsIgnoreCase(userRole);
    boolean isTransportRole = "transport".equalsIgnoreCase(userRole);
    String currentPage = request.getRequestURI();

      out.write("\n");
      out.write("\n");
      out.write("<header class=\"bg-white shadow-md mb-6\">\n");
      out.write("    <div class=\"container mx-auto px-4\">\n");
      out.write("        <div class=\"flex justify-between items-center py-4\">\n");
      out.write("            <!-- Logo and System Name -->\n");
      out.write("            <div class=\"flex items-center\">\n");
      out.write("                <div class=\"bg-primary rounded-full p-2 mr-3\">\n");
      out.write("                    <i class=\"fas fa-bus text-white text-xl\"></i>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <h1 class=\"text-xl font-bold text-gray-800\">Academic Trip System</h1>\n");
      out.write("                    <p class=\"text-xs text-gray-500\">");
      out.print( isLecturerRole ? "Lecturer Portal" : (isTransportRole ? "Transport Management" : "Admin Portal") );
      out.write("</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Navigation Menu -->\n");
      out.write("            <nav class=\"hidden md:flex space-x-6\">\n");
      out.write("                ");
 if(isLecturerRole) { 
      out.write("\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/dashboard.jsp\" \n");
      out.write("                       class=\"");
      out.print( currentPage.contains("/lecturer/dashboard.jsp") ? "text-primary font-medium" : "text-gray-600 hover:text-primary" );
      out.write(" flex items-center transition-colors\">\n");
      out.write("                        <i class=\"fas fa-tachometer-alt mr-2\"></i> Dashboard\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/addTrip.jsp\" \n");
      out.write("                       class=\"");
      out.print( currentPage.contains("/lecturer/addTrip.jsp") ? "text-primary font-medium" : "text-gray-600 hover:text-primary" );
      out.write(" flex items-center transition-colors\">\n");
      out.write("                        <i class=\"fas fa-plus-circle mr-2\"></i> New Trip\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/viewTimetable.jsp\" \n");
      out.write("                       class=\"");
      out.print( currentPage.contains("/lecturer/viewTimetable.jsp") ? "text-primary font-medium" : "text-gray-600 hover:text-primary" );
      out.write(" flex items-center transition-colors\">\n");
      out.write("                        <i class=\"fas fa-calendar-alt mr-2\"></i> Timetable\n");
      out.write("                    </a>\n");
      out.write("                ");
 } else if(isTransportRole) { 
      out.write("\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/dashboard.jsp\" \n");
      out.write("                       class=\"");
      out.print( currentPage.contains("/transport/dashboard.jsp") ? "text-primary font-medium" : "text-gray-600 hover:text-primary" );
      out.write(" flex items-center transition-colors\">\n");
      out.write("                        <i class=\"fas fa-tachometer-alt mr-2\"></i> Dashboard\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/assignResources.jsp\" \n");
      out.write("                       class=\"");
      out.print( currentPage.contains("/transport/assignResources.jsp") ? "text-primary font-medium" : "text-gray-600 hover:text-primary" );
      out.write(" flex items-center transition-colors\">\n");
      out.write("                        <i class=\"fas fa-tasks mr-2\"></i> Assign Resources\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/viewAssignments.jsp\" \n");
      out.write("                       class=\"");
      out.print( currentPage.contains("/transport/viewAssignments.jsp") ? "text-primary font-medium" : "text-gray-600 hover:text-primary" );
      out.write(" flex items-center transition-colors\">\n");
      out.write("                        <i class=\"fas fa-clipboard-list mr-2\"></i> Assignments\n");
      out.write("                    </a>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </nav>\n");
      out.write("            \n");
      out.write("            <!-- User Menu -->\n");
      out.write("            <div class=\"flex items-center\">\n");
      out.write("                ");
 if(headerUser != null) { 
      out.write("\n");
      out.write("                    <div class=\"relative\" id=\"userMenuContainer\">\n");
      out.write("                        <button id=\"userMenuButton\" class=\"flex items-center space-x-2 p-2 rounded-full hover:bg-gray-100 focus:outline-none\">\n");
      out.write("                            <div class=\"h-8 w-8 rounded-full bg-primary flex items-center justify-center\">\n");
      out.write("                                <span class=\"text-white font-medium\">");
      out.print( headerUser.getName() != null ? headerUser.getName().substring(0, 1).toUpperCase() : "U" );
      out.write("</span>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"hidden md:block text-left\">\n");
      out.write("                                <p class=\"text-sm font-medium text-gray-700\">");
      out.print( headerUser.getName() != null ? headerUser.getName() : userRole );
      out.write("</p>\n");
      out.write("                                <p class=\"text-xs text-gray-500\">");
      out.print( userRole );
      out.write("</p>\n");
      out.write("                            </div>\n");
      out.write("                            <i class=\"fas fa-chevron-down text-xs text-gray-400 ml-2\"></i>\n");
      out.write("                        </button>\n");
      out.write("                        \n");
      out.write("                        <!-- Dropdown Menu -->\n");
      out.write("                        <div id=\"userMenu\" class=\"absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-10 hidden\">\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/profile.jsp\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">\n");
      out.write("                                <i class=\"fas fa-user-circle mr-2\"></i> Profile\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"#\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">\n");
      out.write("                                <i class=\"fas fa-key mr-2\"></i> Change Password\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"border-t border-gray-100 my-1\"></div>\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100\">\n");
      out.write("                                <i class=\"fas fa-sign-out-alt mr-2\"></i> Logout\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp\" class=\"text-gray-600 hover:text-primary\">\n");
      out.write("                        <i class=\"fas fa-sign-in-alt mr-2\"></i> Login\n");
      out.write("                    </a>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                \n");
      out.write("                <!-- Mobile menu button -->\n");
      out.write("                <button id=\"mobileMenuButton\" class=\"md:hidden ml-4 focus:outline-none\">\n");
      out.write("                    <i class=\"fas fa-bars text-gray-600 text-xl\"></i>\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Mobile Navigation Menu -->\n");
      out.write("        <div id=\"mobileMenu\" class=\"md:hidden border-t border-gray-200 hidden pb-4 pt-2\">\n");
      out.write("            ");
 if(isLecturerRole) { 
      out.write("\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/dashboard.jsp\" \n");
      out.write("                   class=\"block py-2 px-4 text-gray-600 hover:bg-gray-100 flex items-center\">\n");
      out.write("                    <i class=\"fas fa-tachometer-alt mr-2\"></i> Dashboard\n");
      out.write("                </a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/addTrip.jsp\" \n");
      out.write("                   class=\"block py-2 px-4 text-gray-600 hover:bg-gray-100 flex items-center\">\n");
      out.write("                    <i class=\"fas fa-plus-circle mr-2\"></i> New Trip\n");
      out.write("                </a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/viewTimetable.jsp\" \n");
      out.write("                   class=\"block py-2 px-4 text-gray-600 hover:bg-gray-100 flex items-center\">\n");
      out.write("                    <i class=\"fas fa-calendar-alt mr-2\"></i> Timetable\n");
      out.write("                </a>\n");
      out.write("            ");
 } else if(isTransportRole) { 
      out.write("\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/dashboard.jsp\" \n");
      out.write("                   class=\"block py-2 px-4 text-gray-600 hover:bg-gray-100 flex items-center\">\n");
      out.write("                    <i class=\"fas fa-tachometer-alt mr-2\"></i> Dashboard\n");
      out.write("                </a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/assignResources.jsp\" \n");
      out.write("                   class=\"block py-2 px-4 text-gray-600 hover:bg-gray-100 flex items-center\">\n");
      out.write("                    <i class=\"fas fa-tasks mr-2\"></i> Assign Resources\n");
      out.write("                </a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/viewAssignments.jsp\" \n");
      out.write("                   class=\"block py-2 px-4 text-gray-600 hover:bg-gray-100 flex items-center\">\n");
      out.write("                    <i class=\"fas fa-clipboard-list mr-2\"></i> Assignments\n");
      out.write("                </a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    // Toggle user dropdown menu\n");
      out.write("    document.getElementById('userMenuButton')?.addEventListener('click', function() {\n");
      out.write("        document.getElementById('userMenu').classList.toggle('hidden');\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    // Close the dropdown when clicking outside\n");
      out.write("    document.addEventListener('click', function(event) {\n");
      out.write("        const userMenuContainer = document.getElementById('userMenuContainer');\n");
      out.write("        const userMenu = document.getElementById('userMenu');\n");
      out.write("        if (userMenuContainer && !userMenuContainer.contains(event.target)) {\n");
      out.write("            userMenu.classList.add('hidden');\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    // Mobile menu toggle\n");
      out.write("    document.getElementById('mobileMenuButton')?.addEventListener('click', function() {\n");
      out.write("        document.getElementById('mobileMenu').classList.toggle('hidden');\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"container mx-auto px-4 py-8\">\n");
      out.write("                <!-- Page header -->\n");
      out.write("                <div class=\"md:flex md:items-center md:justify-between mb-8\">\n");
      out.write("                    <div class=\"flex-1 min-w-0\">\n");
      out.write("                        <h1 class=\"text-3xl font-bold text-gray-900\">\n");
      out.write("                            <i class=\"fas fa-calendar-alt mr-2 text-secondary\"></i> Trip Timetable\n");
      out.write("                        </h1>\n");
      out.write("                        <p class=\"mt-1 text-sm text-gray-500\">\n");
      out.write("                            View all scheduled academic trips in the system\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mt-4 md:mt-0\">\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/dashboard.jsp\" \n");
      out.write("                           class=\"bg-gray-500 hover:bg-gray-600 text-white py-2 px-4 rounded-md inline-flex items-center transition-colors\">\n");
      out.write("                            <i class=\"fas fa-arrow-left mr-2\"></i> Back to Dashboard\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Timetable Card -->\n");
      out.write("                <div class=\"bg-white shadow-xl rounded-lg overflow-hidden mb-6\">\n");
      out.write("                    <div class=\"bg-primary px-6 py-4\">\n");
      out.write("                        <div class=\"flex justify-between items-center\">\n");
      out.write("                            <h2 class=\"text-xl font-bold text-white\">\n");
      out.write("                                <i class=\"fas fa-list mr-2\"></i> All Academic Trips\n");
      out.write("                            </h2>\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/addTrip.jsp\" \n");
      out.write("                               class=\"bg-secondary hover:bg-orange-500 text-white py-1.5 px-3 rounded-md inline-flex items-center text-sm transition-colors\">\n");
      out.write("                                <i class=\"fas fa-plus mr-2\"></i> Add Trip\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"p-6\">\n");
      out.write("                        ");
 
                            TripDAO tripDAO = new TripDAO();
                            List<Trip> trips = tripDAO.getAllTrips();
                            
                            if (trips != null && !trips.isEmpty()) { 
                        
      out.write("\n");
      out.write("                        <div class=\"overflow-x-auto\">\n");
      out.write("                            <table class=\"min-w-full divide-y divide-gray-200\">\n");
      out.write("                                <thead>\n");
      out.write("                                    <tr class=\"bg-gray-50\">\n");
      out.write("                                        <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Trip ID</th>\n");
      out.write("                                        <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Departure</th>\n");
      out.write("                                        <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Return</th>\n");
      out.write("                                        <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Destination</th>\n");
      out.write("                                        <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Status</th>\n");
      out.write("                                        <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Course</th>\n");
      out.write("                                        <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Actions</th>\n");
      out.write("                                    </tr>\n");
      out.write("                                </thead>\n");
      out.write("                                <tbody class=\"bg-white divide-y divide-gray-200\">\n");
      out.write("                                    ");
 for (Trip trip : trips) { 
                                        String statusClass = trip.getDriverVehicleId() != null ? "bg-green-100 text-green-800" : "bg-yellow-100 text-yellow-800";
                                        String statusText = trip.getDriverVehicleId() != null ? "Assigned" : "Pending";
                                    
      out.write("\n");
      out.write("                                    <tr class=\"hover:bg-gray-50\">\n");
      out.write("                                        <td class=\"px-6 py-4 whitespace-nowrap text-sm text-gray-500\">\n");
      out.write("                                            ");
      out.print( trip.getTripId() );
      out.write("\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"px-6 py-4 whitespace-nowrap text-sm text-gray-500\">\n");
      out.write("                                            ");
      out.print( trip.getDepartureDate().format(formatter) );
      out.write("\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"px-6 py-4 whitespace-nowrap text-sm text-gray-500\">\n");
      out.write("                                            ");
      out.print( trip.getReturnDate().format(formatter) );
      out.write("\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900\">\n");
      out.write("                                            ");
      out.print( trip.getDestination() != null ? trip.getDestination().getName() : "N/A" );
      out.write("\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"px-6 py-4 whitespace-nowrap\">\n");
      out.write("                                            <span class=\"px-2 inline-flex text-xs leading-5 font-semibold rounded-full ");
      out.print( statusClass );
      out.write("\">\n");
      out.write("                                                ");
      out.print( statusText );
      out.write("\n");
      out.write("                                            </span>\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"px-6 py-4 whitespace-nowrap text-sm text-gray-500\">\n");
      out.write("                                            ");
      out.print( trip.getCourse() != null ? trip.getCourse().getCode() : "N/A" );
      out.write("\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"px-6 py-4 whitespace-nowrap text-sm font-medium\">\n");
      out.write("                                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/viewTrip.jsp?id=");
      out.print( trip.getTripId() );
      out.write("\" \n");
      out.write("                                               class=\"text-indigo-600 hover:text-indigo-900\" title=\"View details\">\n");
      out.write("                                                <i class=\"fas fa-eye\"></i> Details\n");
      out.write("                                            </a>\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                        </div>\n");
      out.write("                        ");
 } else { 
      out.write("\n");
      out.write("                            <div class=\"flex flex-col items-center justify-center py-10\">\n");
      out.write("                                <div class=\"text-center\">\n");
      out.write("                                    <div class=\"rounded-full bg-gray-100 p-6 inline-flex mb-4\">\n");
      out.write("                                        <i class=\"fas fa-calendar-times text-4xl text-gray-400\"></i>\n");
      out.write("                                    </div>\n");
      out.write("                                    <p class=\"text-lg text-gray-600 mb-4\">No trips found in the system.</p>\n");
      out.write("                                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/addTrip.jsp\" class=\"bg-blue-600 hover:bg-blue-700 text-white py-2 px-4 rounded-md inline-flex items-center\">\n");
      out.write("                                        <i class=\"fas fa-plus mr-2\"></i> Create New Trip\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Calendar View (Optional - Advanced Feature) -->\n");
      out.write("                <div class=\"bg-white shadow-xl rounded-lg overflow-hidden mb-6\">\n");
      out.write("                    <div class=\"bg-primary px-6 py-4\">\n");
      out.write("                        <h2 class=\"text-xl font-bold text-white\">\n");
      out.write("                            <i class=\"fas fa-calendar mr-2\"></i> Calendar View\n");
      out.write("                        </h2>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"p-6\">\n");
      out.write("                        <div class=\"bg-gray-50 p-4 rounded-lg border border-gray-200\">\n");
      out.write("                            <p class=\"text-center text-gray-600\">\n");
      out.write("                                <i class=\"fas fa-info-circle mr-1\"></i> \n");
      out.write("                                Calendar view will be available in a future update.\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <footer>\n");
      out.write("            <div class=\"footer-content\">\n");
      out.write("                <p>&copy; ");
      out.print( LocalDate.now().getYear() );
      out.write(" Academic Trip System. All rights reserved.</p>\n");
      out.write("                <p class=\"mt-2 text-sm text-gray-300\">Lecturer Management Module</p>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
