/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-03-11 11:42:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.lecturer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.academictrip.model.User;
import com.academictrip.dao.TripDAO;
import com.academictrip.model.Trip;
import java.util.List;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.DayOfWeek;
import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;
import java.time.temporal.ChronoUnit;
import com.academictrip.model.User;

public final class viewTimetable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1741693180689L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(15);
    _jspx_imports_classes.add("com.academictrip.dao.TripDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.academictrip.model.Trip");
    _jspx_imports_classes.add("java.time.temporal.ChronoUnit");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.time.DayOfWeek");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.academictrip.model.User");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    // Check user authentication
    User timetableUser = (User) session.getAttribute("user");
    if (timetableUser == null || !timetableUser.getRole().equalsIgnoreCase("lecturer")) {
        response.sendRedirect(request.getContextPath() + "/login.jsp");
        return;
    }
    
    // Get lecturer's details
    String lecturerId = String.valueOf(timetableUser.getId());
    String lecturerName = timetableUser.getName();
    String lecturerUsername = timetableUser.getUsername(); // Changed from getEmail() to getUsername()
    
    // Get trips for the lecturer
    TripDAO tripDAO = new TripDAO();
    List<Trip> allTrips = tripDAO.getTripsByLecturerId(lecturerId);
    
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMM yyyy");

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Trip Timetable | Academic Trip System</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/styles.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-gray-50\">\n");
      out.write("    <div class=\"page-wrapper\">\n");
      out.write("        ");
      out.write('\n');
      out.write('\n');

    // Get current user
    User headerUser = (User) session.getAttribute("user");
    
    // Get current page to highlight active menu item
    String currentPage = request.getRequestURI();
    String contextPath = request.getContextPath();
    currentPage = currentPage.substring(currentPage.lastIndexOf("/") + 1);
    
    // Determine user role for menu customization
    boolean isLecturer = headerUser != null && "lecturer".equalsIgnoreCase(headerUser.getRole());
    boolean isAdmin = headerUser != null && "admin".equalsIgnoreCase(headerUser.getRole());
    boolean isDriver = headerUser != null && "driver".equalsIgnoreCase(headerUser.getRole());

      out.write("\n");
      out.write("\n");
      out.write("<header class=\"bg-white shadow-md\">\n");
      out.write("    <div class=\"container mx-auto px-4\">\n");
      out.write("        <div class=\"flex justify-between items-center py-4\">\n");
      out.write("            <!-- Logo -->\n");
      out.write("            <div class=\"flex items-center\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" class=\"text-primary text-2xl font-bold\">\n");
      out.write("                    <i class=\"fas fa-bus mr-2\"></i>\n");
      out.write("                    Academic Trip System\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- User Menu -->\n");
      out.write("            ");
 if (headerUser != null) { 
      out.write("\n");
      out.write("                <div class=\"flex items-center\">\n");
      out.write("                    ");
 if (isLecturer) { 
      out.write("\n");
      out.write("                        <!-- Lecturer Navigation -->\n");
      out.write("                        <nav class=\"hidden md:flex items-center mr-6\">\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/dashboard.jsp\" \n");
      out.write("                               class=\"nav-link ");
      out.print( currentPage.equals("dashboard.jsp") ? "active" : "" );
      out.write("\">\n");
      out.write("                                <i class=\"fas fa-tachometer-alt mr-1\"></i> Dashboard\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/addTrip.jsp\" \n");
      out.write("                               class=\"nav-link ");
      out.print( currentPage.equals("addTrip.jsp") ? "active" : "" );
      out.write("\">\n");
      out.write("                                <i class=\"fas fa-plus-circle mr-1\"></i> New Trip\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/viewTrips.jsp\" \n");
      out.write("                               class=\"nav-link ");
      out.print( currentPage.equals("viewTrips.jsp") ? "active" : "" );
      out.write("\">\n");
      out.write("                                <i class=\"fas fa-list mr-1\"></i> My Trips\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/viewTimetable.jsp\" \n");
      out.write("                               class=\"nav-link ");
      out.print( currentPage.equals("viewTimetable.jsp") ? "active" : "" );
      out.write("\">\n");
      out.write("                                <i class=\"fas fa-calendar-alt mr-1\"></i> Timetable\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/profile.jsp\" \n");
      out.write("                               class=\"nav-link ");
      out.print( currentPage.equals("profile.jsp") ? "active" : "" );
      out.write("\">\n");
      out.write("                                <i class=\"fas fa-user-circle mr-1\"></i> Profile\n");
      out.write("                            </a>\n");
      out.write("                        </nav>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                    \n");
      out.write("                    <!-- User dropdown -->\n");
      out.write("                    <div class=\"relative inline-block text-left\" id=\"userMenu\">\n");
      out.write("                        <div>\n");
      out.write("                            <button type=\"button\" class=\"user-dropdown-button\" id=\"userMenuButton\">\n");
      out.write("                                <div class=\"flex items-center\">\n");
      out.write("                                    <div class=\"h-8 w-8 rounded-full bg-primary flex items-center justify-center text-white text-sm font-medium uppercase\">\n");
      out.write("                                        ");
      out.print( headerUser.getName() != null ? headerUser.getName().substring(0, 1) : "U" );
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    <span class=\"ml-2 hidden md:inline-block text-gray-700\">\n");
      out.write("                                        ");
      out.print( headerUser.getName() != null ? headerUser.getName() : "User" );
      out.write("\n");
      out.write("                                    </span>\n");
      out.write("                                    <i class=\"fas fa-chevron-down ml-2 text-gray-400 text-xs\"></i>\n");
      out.write("                                </div>\n");
      out.write("                            </button>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <!-- Dropdown menu -->\n");
      out.write("                        <div class=\"user-dropdown-menu hidden\" id=\"userDropdownMenu\">\n");
      out.write("                            <div class=\"py-2\">\n");
      out.write("                                <div class=\"px-4 py-2 border-b border-gray-100\">\n");
      out.write("                                    <p class=\"text-sm font-medium text-gray-900\">Signed in as</p>\n");
      out.write("                                    <p class=\"text-sm text-gray-600 truncate\">");
      out.print( headerUser.getUsername() );
      out.write("</p>\n");
      out.write("                                </div>\n");
      out.write("                                \n");
      out.write("                                ");
 if (isLecturer) { 
      out.write("\n");
      out.write("                                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/profile.jsp\" class=\"dropdown-item\">\n");
      out.write("                                        <i class=\"fas fa-user-circle mr-2 text-gray-500\"></i> Profile\n");
      out.write("                                    </a>\n");
      out.write("                                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/dashboard.jsp\" class=\"dropdown-item\">\n");
      out.write("                                        <i class=\"fas fa-tachometer-alt mr-2 text-gray-500\"></i> Dashboard\n");
      out.write("                                    </a>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                                \n");
      out.write("                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\" class=\"dropdown-item border-t border-gray-100 text-red-600 hover:text-red-800 hover:bg-red-50\">\n");
      out.write("                                    <i class=\"fas fa-sign-out-alt mr-2\"></i> Sign out\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <!-- Mobile menu button -->\n");
      out.write("                    <div class=\"ml-4 md:hidden\">\n");
      out.write("                        <button type=\"button\" id=\"mobileMenuButton\" class=\"text-gray-500 hover:text-gray-700 focus:outline-none\">\n");
      out.write("                            <i class=\"fas fa-bars text-lg\"></i>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <!-- Not logged in -->\n");
      out.write("                <div>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp\" class=\"btn-outline\">\n");
      out.write("                        <i class=\"fas fa-sign-in-alt mr-1\"></i> Login\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Mobile menu -->\n");
      out.write("        ");
 if (headerUser != null) { 
      out.write("\n");
      out.write("            <div class=\"md:hidden hidden\" id=\"mobileMenu\">\n");
      out.write("                <div class=\"pt-2 pb-4 border-t border-gray-200\">\n");
      out.write("                    ");
 if (isLecturer) { 
      out.write("\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/dashboard.jsp\" \n");
      out.write("                           class=\"mobile-nav-link ");
      out.print( currentPage.equals("dashboard.jsp") ? "bg-primary text-white" : "" );
      out.write("\">\n");
      out.write("                            <i class=\"fas fa-tachometer-alt mr-2\"></i> Dashboard\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/addTrip.jsp\" \n");
      out.write("                           class=\"mobile-nav-link ");
      out.print( currentPage.equals("addTrip.jsp") ? "bg-primary text-white" : "" );
      out.write("\">\n");
      out.write("                            <i class=\"fas fa-plus-circle mr-2\"></i> New Trip\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/viewTrips.jsp\" \n");
      out.write("                           class=\"mobile-nav-link ");
      out.print( currentPage.equals("viewTrips.jsp") ? "bg-primary text-white" : "" );
      out.write("\">\n");
      out.write("                            <i class=\"fas fa-list mr-2\"></i> My Trips\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/viewTimetable.jsp\" \n");
      out.write("                           class=\"mobile-nav-link ");
      out.print( currentPage.equals("viewTimetable.jsp") ? "bg-primary text-white" : "" );
      out.write("\">\n");
      out.write("                            <i class=\"fas fa-calendar-alt mr-2\"></i> Timetable\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/profile.jsp\" \n");
      out.write("                           class=\"mobile-nav-link ");
      out.print( currentPage.equals("profile.jsp") ? "bg-primary text-white" : "" );
      out.write("\">\n");
      out.write("                            <i class=\"fas fa-user-circle mr-2\"></i> Profile\n");
      out.write("                        </a>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\" class=\"mobile-nav-link text-red-600\">\n");
      out.write("                        <i class=\"fas fa-sign-out-alt mr-2\"></i> Sign out\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<!-- Add necessary CSS for the header -->\n");
      out.write("<style>\n");
      out.write("    .nav-link {\n");
      out.write("        @apply px-4 py-2 text-gray-700 hover:text-primary transition-colors;\n");
      out.write("    }\n");
      out.write("    .nav-link.active {\n");
      out.write("        @apply text-primary font-medium;\n");
      out.write("    }\n");
      out.write("    .dropdown-item {\n");
      out.write("        @apply block w-full px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 cursor-pointer;\n");
      out.write("    }\n");
      out.write("    .user-dropdown-button {\n");
      out.write("        @apply inline-flex justify-center w-full rounded-md px-3 py-2 bg-white hover:bg-gray-50 focus:outline-none;\n");
      out.write("    }\n");
      out.write("    .user-dropdown-menu {\n");
      out.write("        @apply absolute right-0 w-56 mt-2 origin-top-right bg-white rounded-md shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none z-10;\n");
      out.write("    }\n");
      out.write("    .mobile-nav-link {\n");
      out.write("        @apply block px-4 py-3 text-base font-medium text-gray-700 hover:bg-gray-100 transition-colors;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<!-- JavaScript for the header dropdowns and mobile menu -->\n");
      out.write("<script>\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("        const userMenuButton = document.getElementById('userMenuButton');\n");
      out.write("        const userDropdownMenu = document.getElementById('userDropdownMenu');\n");
      out.write("        const mobileMenuButton = document.getElementById('mobileMenuButton');\n");
      out.write("        const mobileMenu = document.getElementById('mobileMenu');\n");
      out.write("        \n");
      out.write("        // Handle user dropdown toggle\n");
      out.write("        if (userMenuButton && userDropdownMenu) {\n");
      out.write("            userMenuButton.addEventListener('click', function() {\n");
      out.write("                userDropdownMenu.classList.toggle('hidden');\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            // Close dropdown when clicking outside\n");
      out.write("            document.addEventListener('click', function(event) {\n");
      out.write("                if (!userMenuButton.contains(event.target) && !userDropdownMenu.contains(event.target)) {\n");
      out.write("                    userDropdownMenu.classList.add('hidden');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        // Handle mobile menu toggle\n");
      out.write("        if (mobileMenuButton && mobileMenu) {\n");
      out.write("            mobileMenuButton.addEventListener('click', function() {\n");
      out.write("                mobileMenu.classList.toggle('hidden');\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"container mx-auto px-4 py-8\">\n");
      out.write("                <!-- Page header -->\n");
      out.write("                <div class=\"md:flex md:items-center md:justify-between mb-8\">\n");
      out.write("                    <div class=\"flex-1 min-w-0\">\n");
      out.write("                        <h1 class=\"text-3xl font-bold text-gray-900\">\n");
      out.write("                            <i class=\"fas fa-calendar-alt mr-2 text-secondary\"></i> Trip Timetable\n");
      out.write("                        </h1>\n");
      out.write("                        <p class=\"mt-1 text-sm text-gray-500\">\n");
      out.write("                            View all scheduled academic trips in the system\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mt-4 md:mt-0\">\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/dashboard.jsp\" \n");
      out.write("                           class=\"bg-gray-500 hover:bg-gray-600 text-white py-2 px-4 rounded-md inline-flex items-center transition-colors\">\n");
      out.write("                            <i class=\"fas fa-arrow-left mr-2\"></i> Back to Dashboard\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Timetable Card -->\n");
      out.write("                <div class=\"bg-white shadow-xl rounded-lg overflow-hidden mb-6\">\n");
      out.write("                    <div class=\"bg-primary px-6 py-4\">\n");
      out.write("                        <div class=\"flex justify-between items-center\">\n");
      out.write("                            <h2 class=\"text-xl font-bold text-white\">\n");
      out.write("                                <i class=\"fas fa-list mr-2\"></i> All Academic Trips\n");
      out.write("                            </h2>\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/addTrip.jsp\" \n");
      out.write("                               class=\"bg-secondary hover:bg-orange-500 text-white py-1.5 px-3 rounded-md inline-flex items-center text-sm transition-colors\">\n");
      out.write("                                <i class=\"fas fa-plus mr-2\"></i> Add Trip\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"p-6\">\n");
      out.write("                        ");
 
                            
                            List<Trip> trips = tripDAO.getAllTrips();
                            
                            if (trips != null && !trips.isEmpty()) { 
                        
      out.write("\n");
      out.write("                        <div class=\"overflow-x-auto\">\n");
      out.write("                            <table class=\"min-w-full divide-y divide-gray-200\">\n");
      out.write("                                <thead>\n");
      out.write("                                    <tr class=\"bg-gray-50\">\n");
      out.write("                                        <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Trip ID</th>\n");
      out.write("                                        <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Departure</th>\n");
      out.write("                                        <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Return</th>\n");
      out.write("                                        <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Destination</th>\n");
      out.write("                                        <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Status</th>\n");
      out.write("                                        <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Course</th>\n");
      out.write("                                        <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Actions</th>\n");
      out.write("                                    </tr>\n");
      out.write("                                </thead>\n");
      out.write("                                <tbody class=\"bg-white divide-y divide-gray-200\">\n");
      out.write("                                    ");
 for (Trip trip : trips) { 
                                        String statusClass = trip.getDriverVehicleId() != null ? "bg-green-100 text-green-800" : "bg-yellow-100 text-yellow-800";
                                        String statusText = trip.getDriverVehicleId() != null ? "Assigned" : "Pending";
                                    
      out.write("\n");
      out.write("                                    <tr class=\"hover:bg-gray-50\">\n");
      out.write("                                        <td class=\"px-6 py-4 whitespace-nowrap text-sm text-gray-500\">\n");
      out.write("                                            ");
      out.print( trip.getTripId() );
      out.write("\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"px-6 py-4 whitespace-nowrap text-sm text-gray-500\">\n");
      out.write("                                            ");
      out.print( trip.getDepartureDate().format(formatter) );
      out.write("\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"px-6 py-4 whitespace-nowrap text-sm text-gray-500\">\n");
      out.write("                                            ");
      out.print( trip.getReturnDate().format(formatter) );
      out.write("\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900\">\n");
      out.write("                                            ");
      out.print( trip.getDestination() != null ? trip.getDestination().getName() : "N/A" );
      out.write("\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"px-6 py-4 whitespace-nowrap\">\n");
      out.write("                                            <span class=\"px-2 inline-flex text-xs leading-5 font-semibold rounded-full ");
      out.print( statusClass );
      out.write("\">\n");
      out.write("                                                ");
      out.print( statusText );
      out.write("\n");
      out.write("                                            </span>\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"px-6 py-4 whitespace-nowrap text-sm text-gray-500\">\n");
      out.write("                                            ");
      out.print( trip.getCourse() != null ? trip.getCourse().getCode() : "N/A" );
      out.write("\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"px-6 py-4 whitespace-nowrap text-sm font-medium\">\n");
      out.write("                                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/viewTrip.jsp?id=");
      out.print( trip.getTripId() );
      out.write("\" \n");
      out.write("                                               class=\"text-indigo-600 hover:text-indigo-900\" title=\"View details\">\n");
      out.write("                                                <i class=\"fas fa-eye\"></i> Details\n");
      out.write("                                            </a>\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                        </div>\n");
      out.write("                        ");
 } else { 
      out.write("\n");
      out.write("                            <div class=\"flex flex-col items-center justify-center py-10\">\n");
      out.write("                                <div class=\"text-center\">\n");
      out.write("                                    <div class=\"rounded-full bg-gray-100 p-6 inline-flex mb-4\">\n");
      out.write("                                        <i class=\"fas fa-calendar-times text-4xl text-gray-400\"></i>\n");
      out.write("                                    </div>\n");
      out.write("                                    <p class=\"text-lg text-gray-600 mb-4\">No trips found in the system.</p>\n");
      out.write("                                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lecturer/addTrip.jsp\" class=\"bg-blue-600 hover:bg-blue-700 text-white py-2 px-4 rounded-md inline-flex items-center\">\n");
      out.write("                                        <i class=\"fas fa-plus mr-2\"></i> Create New Trip\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Calendar View (Optional - Advanced Feature) -->\n");
      out.write("                <div class=\"bg-white shadow-xl rounded-lg overflow-hidden mb-6\">\n");
      out.write("                    <div class=\"bg-primary px-6 py-4\">\n");
      out.write("                        <h2 class=\"text-xl font-bold text-white\">\n");
      out.write("                            <i class=\"fas fa-calendar mr-2\"></i> Calendar View\n");
      out.write("                        </h2>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"p-6\">\n");
      out.write("                        <div class=\"bg-gray-50 p-4 rounded-lg border border-gray-200\">\n");
      out.write("                            <p class=\"text-center text-gray-600\">\n");
      out.write("                                <i class=\"fas fa-info-circle mr-1\"></i> \n");
      out.write("                                Calendar view will be available in a future update.\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <footer>\n");
      out.write("            <div class=\"footer-content\">\n");
      out.write("                <p>&copy; ");
      out.print( LocalDate.now().getYear() );
      out.write(" Academic Trip System. All rights reserved.</p>\n");
      out.write("                <p class=\"mt-2 text-sm text-gray-300\">Lecturer Management Module</p>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
